eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080


spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:

        - id: slot-booking-service
          uri: http://localhost:8087
          predicates:
            - Path=/slot-booking-service/**
          filters:
            - RewritePath=/slot-booking-service(?<segment>/?.*), $\{segment}


        - id: vaccination-center-service
          uri: http://localhost:8084
          predicates:
            - Path=/vaccination-center-service/**
          filters:
            - RewritePath=/vaccination-center-service(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8085
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8095
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: http://localhost:4200
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}
